version: '3.1'
services :
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080
